### PR TITLE
Use Cmd+B to source() the current file in R.

### PR DESCRIPTION
**Pull request by rodrigorgs**
Just a small feature that I needed for my workflow. Hope you find it useful.

### CODE REVIEW

**Comment by vqv** [comment]
Cmd+B ("super+b") conflicts with the default keybinding for "build". See the file `Packages/Default/Default (OSX).sublime-keymap`:

```
    { "keys": ["super+b"], "command": "build" },
```

Maybe it would be possible to setup a build system for R so that "build" command either launches R in batch mode, or sources the current file in the R GUI?

**Comment by rodrigorgs** [comment]
@vqv you are right. I've chosen the Cmd+B keybinding to emulate "build", but I wasn't aware there was a customizable build system in ST2. In this case, it would be better to revert my patch and just add a `R.sublime-build` file with the following contents:

``` json
{
  "cmd": ["osascript", "-e", "tell app \"R64\" to cmd \"source('$file')\"\n"]
}
```

The command opens the R GUI if it is closed, then sources the current file.

**Comment by karthik** [comment]
I reset the branch to the last working commit for the time being.

**Comment by karthik** [comment]
@vqv I've fixed the issue. Let me know if this works for you so I can close this up.

**Comment by rodrigorgs** [comment]
@karthikram The class `SourceFileCommand` is not needed anymore and can be removed from `Rtools.py`.

**Comment by vqv** [comment]
@karthikram The keybinding no longer conflicts, but the build system is not working.  I'm not sure why.

**Comment by rodrigorgs** [comment]
@vqv Have you tried restarting ST2?

**Comment by karthik** [comment]
@vqv Try now...I removed the `SourceFileCommand` class from rtools.py

**Pull request merged**
